### ISSUE TITLE
Sensoren werden nicht angelernt

### ISSUE THREAD

**Issue by ghost** [ioBroker/ioBroker.mysensors#11]
Hallo
Das Einbinden meiner MySensor Temperatur Sensoren in ioBroker funktioniert leider nicht.
Ich verwende ein MySensor WLAN Gateway. Die Sensoren verbinden sich mit dem Gateway. 
In ioBroker kann ich das WLAN Gateway dann per TCP-Client einbinden. 
Den Anlernmodus habe ich aktiviert und im debug Modus kommen folgende Werte an.

<code>
Message type: set
Got: {"id":"101","childId":"0","type":"set","ack":false,"payload":"69.5","subType":"V_HUM"}
TCP data received from: 101;0;1;0;1;69.5
Message type: set
Got: {"id":"101","childId":"1","type":"set","ack":false,"payload":"0.6","subType":"V_TEMP"}
TCP data received from: 101;1;1;0;0;0.6
</code>

Die Sensoren werden allerdings nicht eingebunden.
Ich habe das Ganze mittlerweile auch mit einem per USB angebundenen MySeonsors Gateway probiert. Auch hier kommen die Werte der Sensoren an werden aber nicht in ioBroker angelegt.
Kann mir jemand sagen, was ich machen muss damit die Sensoren angelegt werden ?
Vielen Dank im Voraus.

**Comment by Haba1234** [comment]
Hi!
Is the object "mysensors.0.inclusionOn" set to true?

**Comment by ghost** [comment]
Hi Haba1234
Yes. The inclusionOn is set to true.

**Comment by Haba1234** [comment]
Please copy the complete log when debugging is enabled at the time power is applied to your node.
What is your version of the library MySensors on the host and gateway?
What version of the adapter is installed?
