### ISSUE TITLE
BME280 HUM value missing

### ISSUE THREAD

**Issue by sevelen** [ioBroker/ioBroker.mysensors#14]
IoBroker shows the Temp and Pressure value but Hum is missing. 

`mysensors.0	2019-09-05 18:55:48.532	info	Add new object: 1.0_TEMP.V_ID - 1.0_TEMP.V_ID
mysensors.0	2019-09-05 18:55:48.531	info	Add new object: 1.0_TEMP.V_TEMP - 1.0_TEMP.V_TEMP
mysensors.0	2019-09-05 18:55:48.530	info	Add new object: 1.0_TEMP - 1.0_TEMP
mysensors.0	2019-09-05 18:55:48.475	info	Add new object: 1.2_BARO.V_FORECAST - 1.2_BARO.V_FORECAST
mysensors.0	2019-09-05 18:55:48.475	info	Add new object: 1.2_BARO.V_PRESSURE - 1.2_BARO.V_PRESSURE
mysensors.0	2019-09-05 18:55:48.474	info	Add new object: 1.2_BARO - 1.2_BARO
mysensors.0	2019-09-05 18:55:48.416	info	Version :1.1
mysensors.0	2019-09-05 18:55:48.356	warn	setObject mysensors.0.1 (type=device) property native missing!
mysensors.0	2019-09-05 18:55:48.353	info	Name :BME280 Sensor`

**Comment by jangatzke** [comment]
This could be an error in your sketch. I have a BME280 node working without problems.

**Comment by Emilleopold** [comment]
In my case there is also the V_HUM missing in IOBroker. I have a ESP8266WLAN Gateway. The data is send from the GW because when I add the V_HUM manually in the OBJECTS I get the value. With another sensor I have also 3 values and only 2 values were generated in IOBroker. When I add the third value manually, it works.

**Comment by Emilleopold** [comment]
I searched again for a solution and found the reason.
The nrf2rfm69 radio has only a small data buffer and so the presentation of the third (and following) measurement is missing.
put a wait(200); between all measurements in the presentation() routine and it works.
