### ISSUE TITLE
Adapter wrong interpretation of protocol 2.x

### ISSUE THREAD

**Issue by dragospascale** [ioBroker/ioBroker.mysensors#5]
A node sends a request for variable value like :
1;2;2;0;2;
and interprets as :
Got: {"id":"1","childId":"2","type":"req","ack":false,"payload":"","subType":"V_LIGHT"}
V_Light does not exists anymore in 2.x protocol
Instead 2 should be translated to V_STATUS
Controller does not respond to request

**Comment by dragospascale** [comment]
Solved 👍
Change in node_modules/sensors/lib/values.js
line 56, 77, 116, 137 V_LIGHT to V_STATUS
and it works Controller responds with set value

**Comment by Haba1234** [comment]
Added in version 1.2.2
