### ISSUE TITLE
Messages of type V_VAR1 are ignored?!

### ISSUE THREAD

**Issue by cimba007** [ioBroker/ioBroker.mysensors#6]
Hello,

currently I have a 433mhz receiver on my mysensors gateway.

There are two types of messages that should be received by iobroker

1. actual value of received packet
2. rssi

The rssi values are calculated on the gateway and are send along with thie code of the received package (a few seconds later)

![image](https://user-images.githubusercontent.com/3453121/37531675-1e57b322-293d-11e8-8de2-3818bcb8b7d7.png)

gateway sketch  (only the most important parts):
```
MyMessage msg[12];
MyMessage msg_rssi[12];

present(7, S_DOOR);

msg[7].setSensor(7);  msg[7].setType(V_TRIPPED);
msg_rssi[7].setSensor(7);  msg_rssi[7].setType(V_VAR1);

send(msg_rssi[i].set(rssi));

      else if (code == XXX)
      {
        // Reed (2)
        send(msg[7].set(1));
        send(msg[7].set(0));
        rssi_current_count[7]++;
        last_tripped = millis();
        tripped = true;
      }
```

On iobroker I can only see the V_TRIPPED values but not the V_VAR1 values (representing my rssi value)

Is there a way to enable debugging for this adapter to see where the values got missing?

I also get stuff like this when the gateways starts:

```
mysensors.0 | 2018-03-16 17:15:32.925 | warn | ID not found. Inclusion mode OFF: {"id":"0","childId":"7","type":"presentation","ack":false,"payload":"","subType":"S_DOOR"}
-- | -- | -- | --
```

Edit: I tried to change but nothing changed

```
var presentation = {
    'S_DOOR':               {index: 0,  role: 'door',              vars: ['V_TRIPPED','V_VAR1']},
    'S_MOTION':             {index: 1,  role: 'motion',            vars: ['V_TRIPPED','V_VAR1']},
```

**Comment by cimba007** [comment]
I got it going doing a "double" presentation which seems to be just wrong:

![image](https://user-images.githubusercontent.com/3453121/37533740-0d250c16-2943-11e8-98bc-529b82e0fc42.png)

  present(7, S_DOOR);
  present(7, S_CUSTOM);

**Comment by GermanBluefox** [comment]
Am I understand you right: you send S_DOOR (V_TRIPPED, V_VAR1) and in V_VAR1 is rssi and you cant see rssi in broker?

**Comment by cimba007** [comment]
In my original setup I have one Sensor:

S_DOOR

So door does contain two different messages

V_TRIPPED (every time a packet is received) and
V_VAR1 which is a calculated RSSI value

I could only see V_TRIPPED.

Later I changed my sketch to do:

```
  present(7, S_DOOR);     present(7, S_CUSTOM);
```

Now it is working as 7_CUSTOM is creadted which now contains VAR1. I will stick to this solution as no change on the ioBroker.mysensors implementation is need

**Comment by GermanBluefox** [comment]
Ok.
