### ISSUE TITLE
S_BARO, S_TEMP wrong

### ISSUE THREAD

**Issue by elmarfaber** [ioBroker/ioBroker.mysensors#7]
Hello,
I have two sensors with a temperatue sensor and a pressure sensor.
I init the sensor with 
  present(CHILD_ID_Temp, S_TEMP, "Ausentemperatur");
  present(CHILD_ID_Baro, S_BARO, "Luftdruck");  
in ioBroker I only get V_PRESSURE value for S_BARO and
V_TEMP for S_TEMP.
But S_TEMP has two variables V_TEMP and V_ID and S_BARO has two variables too
V_PRESSURE ans V_FORECAST

Additional V_Pressure has max of 100 and unit of % ans thats wrong.

Are there a possibillity to correct this ?

Thank you very much
Best regards

**Comment by Apollon77** [comment]
Can you send please what exactly is incoming to the adapter? Try debug log.

**Comment by elmarfaber** [comment]
This is the log from ioBroker:

mysensors.0 | 2018-03-30 18:41:43.657 | info | Add new object: 192_168_178_23.25.6_HUM.V_HUM - Luftfeuchtigkeit.V_HUM
-- | -- | -- | --
mysensors.0 | 2018-03-30 18:41:43.643 | info | Add new object: 192_168_178_23.25.6_HUM - Luftfeuchtigkeit
mysensors.0 | 2018-03-30 18:41:43.427 | info | Add new object: 192_168_178_23.25.5_BARO.V_PRESSURE - Luftdruck.V_PRESSURE
mysensors.0 | 2018-03-30 18:41:43.424 | info | Add new object: 192_168_178_23.25.5_BARO - Luftdruck
mysensors.0 | 2018-03-30 18:41:43.224 | info | Add new object: 192_168_178_23.25.4_TEMP.V_TEMP - Innentemperatur.V_TEMP
mysensors.0 | 2018-03-30 18:41:43.221 | info | Add new object: 192_168_178_23.25.4_TEMP - Innentemperatur
mysensors.0 | 2018-03-30 18:41:43.013 | info | Add new object: 192_168_178_23.25.3_TEMP.V_TEMP - Ausentemperatur.V_TEMP
mysensors.0 | 2018-03-30 18:41:43.011 | info | Add new object: 192_168_178_23.25.3_TEMP - Ausentemperatur
mysensors.0 | 2018-03-30 18:41:42.803 | info | Add new object: 192_168_178_23.25.2_CUSTOM.V_VAR5 - Buttons.V_VAR5
mysensors.0 | 2018-03-30 18:41:42.801 | info | Add new object: 192_168_178_23.25.2_CUSTOM.V_VAR4 - Buttons.V_VAR4
mysensors.0 | 2018-03-30 18:41:42.800 | info | Add new object: 192_168_178_23.25.2_CUSTOM.V_VAR3 - Buttons.V_VAR3
mysensors.0 | 2018-03-30 18:41:42.799 | info | Add new object: 192_168_178_23.25.2_CUSTOM.V_VAR2 - Buttons.V_VAR2
mysensors.0 | 2018-03-30 18:41:42.798 | info | Add new object: 192_168_178_23.25.2_CUSTOM.V_VAR1 - Buttons.V_VAR1
mysensors.0 | 2018-03-30 18:41:42.796 | info | Add new object: 192_168_178_23.25.2_CUSTOM - Buttons
mysensors.0 | 2018-03-30 18:41:42.595 | info | Add new object: 192_168_178_23.25.1_CUSTOM.V_VAR5 - Müllstatus.V_VAR5
mysensors.0 | 2018-03-30 18:41:42.594 | info | Add new object: 192_168_178_23.25.1_CUSTOM.V_VAR4 - Müllstatus.V_VAR4
mysensors.0 | 2018-03-30 18:41:42.590 | info | Add new object: 192_168_178_23.25.1_CUSTOM.V_VAR3 - Müllstatus.V_VAR3
mysensors.0 | 2018-03-30 18:41:42.589 | info | Add new object: 192_168_178_23.25.1_CUSTOM.V_VAR2 - Müllstatus.V_VAR2
mysensors.0 | 2018-03-30 18:41:42.588 | info | Add new object: 192_168_178_23.25.1_CUSTOM.V_VAR1 - Müllstatus.V_VAR1
mysensors.0 | 2018-03-30 18:41:42.586 | info | Add new object: 192_168_178_23.25.1_CUSTOM - Müllstatus
mysensors.0 | 2018-03-30 18:41:42.499 | info | Add new object: 192_168_178_23.25.0_INFO.V_TEXT - 192_168_178_23.25.0_INFO.V_TEXT
mysensors.0 | 2018-03-30 18:41:42.497 | info | Add new object: 192_168_178_23.25.0_INFO - 192_168_178_23.25.0_INFO

**Comment by elmarfaber** [comment]
This the debug from mySensors:
 __  __       ____
|  \/  |_   _/ ___|  ___ _ __  ___  ___  _ __ ___
| |\/| | | | \___ \ / _ \ `_ \/ __|/ _ \| `__/ __|
| |  | | |_| |___| |  __/ | | \__ \  _  | |  \__ \
|_|  |_|\__, |____/ \___|_| |_|___/\___/|_|  |___/
        |___/                      2.2.0

16 MCO:BGN:INIT NODE,CP=RNNNA---,VER=2.2.0
25 TSM:INIT
26 TSF:WUR:MS=0
33 TSM:INIT:TSP OK
35 TSM:INIT:STATID=25
37 TSF:SID:OK,ID=25
39 TSM:FPAR
75 TSF:MSG:SEND,25-25-255-255,s=255,c=3,t=7,pt=0,l=0,sg=0,ft=0,st=OK:
579 TSF:MSG:READ,0-0-25,s=255,c=3,t=8,pt=1,l=1,sg=0:0
584 TSF:MSG:FPAR OK,ID=0,D=1
2083 TSM:FPAR:OK
2084 TSM:ID
2085 TSM:ID:OK
2087 TSM:UPL
2091 TSF:MSG:SEND,25-25-0-0,s=255,c=3,t=24,pt=1,l=1,sg=0,ft=0,st=OK:1
2201 TSF:MSG:READ,0-0-25,s=255,c=3,t=25,pt=1,l=1,sg=0:1
2206 TSF:MSG:PONG RECV,HP=1
2208 TSM:UPL:OK
2210 TSM:READY:ID=25,PAR=0,DIS=1
2215 TSF:MSG:SEND,25-25-0-0,s=255,c=3,t=15,pt=6,l=2,sg=0,ft=0,st=OK:0100
2354 TSF:MSG:READ,0-0-25,s=255,c=3,t=15,pt=6,l=2,sg=0:0100
2362 TSF:MSG:SEND,25-25-0-0,s=255,c=0,t=17,pt=0,l=5,sg=0,ft=0,st=OK:2.2.0
2370 TSF:MSG:SEND,25-25-0-0,s=255,c=3,t=6,pt=1,l=1,sg=0,ft=0,st=OK:0
4378 TSF:MSG:SEND,25-25-0-0,s=255,c=3,t=11,pt=0,l=14,sg=0,ft=0,st=OK:Control-Center
4387 TSF:MSG:SEND,25-25-0-0,s=255,c=3,t=12,pt=0,l=3,sg=0,ft=0,st=OK:1.0
4396 TSF:MSG:SEND,25-25-0-0,s=0,c=0,t=36,pt=0,l=0,sg=0,ft=0,st=OK:
4606 TSF:MSG:SEND,25-25-0-0,s=1,c=0,t=23,pt=0,l=11,sg=0,ft=0,st=OK:Müllstatus
4816 TSF:MSG:SEND,25-25-0-0,s=2,c=0,t=23,pt=0,l=7,sg=0,ft=0,st=OK:Buttons
5025 TSF:MSG:SEND,25-25-0-0,s=3,c=0,t=6,pt=0,l=15,sg=0,ft=0,st=OK:Ausentemperatur
5235 TSF:MSG:SEND,25-25-0-0,s=4,c=0,t=6,pt=0,l=15,sg=0,ft=0,st=OK:Innentemperatur
5445 TSF:MSG:SEND,25-25-0-0,s=5,c=0,t=8,pt=0,l=9,sg=0,ft=0,st=OK:Luftdruck
5657 TSF:MSG:SEND,25-25-0-0,s=6,c=0,t=7,pt=0,l=16,sg=0,ft=0,st=OK:Luftfeuchtigkeit
6165 MCO:REG:REQ
6168 TSF:MSG:SEND,25-25-0-0,s=255,c=3,t=26,pt=1,l=1,sg=0,ft=0,st=OK:2
6240 TSF:MSG:READ,0-0-25,s=255,c=3,t=27,pt=1,l=1,sg=0:1
6245 MCO:PIM:NODE REG=1
6248 MCO:BGN:STP
6249 MCO:SLP:MS=500,SMS=0,I1=255,M1=255,I2=255,M2=255
6254 TSF:TDI:TSL
6256 MCO:SLP:WUP=-1
6258 TSF:TRI:TSB
6517 TSF:MSG:SEND,25-25-0-0,s=1,c=2,t=24,pt=0,l=0,sg=0,ft=0,st=OK:
6726 TSF:MSG:SEND,25-25-0-0,s=1,c=2,t=25,pt=0,l=0,sg=0,ft=0,st=OK:
6935 TSF:MSG:SEND,25-25-0-0,s=1,c=2,t=26,pt=0,l=0,sg=0,ft=0,st=OK:
7142 TSF:MSG:SEND,25-25-0-0,s=1,c=2,t=27,pt=0,l=0,sg=0,ft=0,st=OK:
7552 TSF:MSG:SEND,25-25-0-0,s=3,c=2,t=0,pt=0,l=0,sg=0,ft=0,st=OK:
7759 TSF:MSG:SEND,25-25-0-0,s=4,c=2,t=0,pt=0,l=0,sg=0,ft=0,st=OK:
7967 TSF:MSG:SEND,25-25-0-0,s=5,c=2,t=4,pt=0,l=0,sg=0,ft=0,st=OK:
8176 TSF:MSG:SEND,25-25-0-0,s=6,c=2,t=1,pt=0,l=0,sg=0,ft=0,st=OK:
9509 MCO:BGN:INIT OK,TSP=1
60002 TSF:MSG:SEND,25-25-0-0,s=5,c=1,t=5,pt=0,l=7,sg=0,ft=0,st=OK:unknown
60010 TSF:MSG:SEND,25-25-0-0,s=255,c=3,t=1,pt=0,l=0,sg=0,ft=0,st=OK:
60447 TSF:MSG:READ,0-0-25,s=255,c=3,t=1,pt=0,l=10,sg=0:1522428467
60453 TSF:MSG:ACK REQ
60457 TSF:MSG:SEND,25-25-0-0,s=255,c=3,t=1,pt=0,l=10,sg=0,ft=0,st=OK:1522428467

**Comment by elmarfaber** [comment]
{
  "common": {
    "name": "Luftdruck.V_PRESSURE",
    "type": "number",
    "role": "value.pressure",
    "unit": "%",
    "min": 0,
    "max": 100,
    "def": 0,
    "read": true,
    "write": false
  },
  "native": {
    "ip": "192.168.178.23",
    "id": "25",
    "childId": "5",
    "subType": "S_BARO",
    "varType": "V_PRESSURE",
    "subTypeNum": 8,
    "varTypeNum": 4
  },
  "acl": {
    "object": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator",
    "state": 1636
  },
  "_id": "mysensors.0.192_168_178_23.25.5_BARO.V_PRESSURE",
  "type": "state"
}

**Comment by elmarfaber** [comment]
"raw" from ioBroker

**Comment by elmarfaber** [comment]
var presentation = {
... 
shoud be:
'S_TEMP':               {index: 6,  role: 'temperature',       vars: ['V_TEMP', 'V_ID']},
'S_BARO':               {index: 8,  role: 'pressure',          vars: ['V_PRESSURE', 'V_FORECAST']},

var vars = {
    'V_PRESSURE':           {index: 4,  role: 'value',     type: 'number',     read: true, write: false, def: 0, min: 0, max: 100, unit: '%'},     //Atmospheric Pressure
should be:
    'V_PRESSURE':           {index: 4,  role: 'value',     type: 'number',     read: true, write: false, def: 0, min: 0, max: 1200, unit: 'hPa'},     //Atmospheric Pressure

**Comment by Haba1234** [comment]
Hi! 
Added in version 1.2.2
